default: install
install:
	$(MAKE) -C service-one install
	$(MAKE) -C service-two install
	$(MAKE) -C service-three install
uninstall:
	$(MAKE) -C service-one uninstall
	$(MAKE) -C service-two uninstall
	$(MAKE) -C service-three uninstall